# Generated by Django 6.1 on 2026-08-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanagrin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress ', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
