# Generated by Django 6.1 on 2026-08-18 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hanagrin', '0002_subtask_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name': 'Priority', 'verbose_name_plural': 'Priorities'},
        ),
    ]
